/**************************************************************************/
/*  VoxelGenerator.h                                                      */
/**************************************************************************/
/*                         This file is part of:                          */
/*                             KEEN VOXEL ENGINE                          */
/*                        https://keenvoxelengine.org                     */
/**************************************************************************/
/* Copyright (c) 2025-present Keen Voxel Engine                           */
/*                   All rights reserved.                                 */
/*                                                                        */
/* Permission is hereby granted, free of charge, to any person obtaining  */
/* a copy of this software and associated documentation files (the        */
/* "Software"), to deal in the Software without restriction, including    */
/* without limitation the rights to use, copy, modify, merge, publish,    */
/* distribute, sublicense, and/or sell copies of the Software, and to     */
/* permit persons to whom the Software is furnished to do so, subject to  */
/* the following conditions:                                              */
/*                                                                        */
/* The above copyright notice and this permission notice shall be         */
/* included in all copies or substantial portions of the Software.        */
/*                                                                        */
/* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,        */
/* EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF     */
/* MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. */
/* IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY   */
/* CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,   */
/* TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE      */
/* SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.                 */
/**************************************************************************/

#ifndef VOXEL_GENERATOR_H
#define VOXEL_GENERATOR_H

// We don't need windows.h in this example plugin but many others do, and it can
// lead to annoying situations due to the ton of macros it defines.
// So we include it and make sure CI warns us if we use something that conflicts
// with a Windows define.
#ifdef WIN32
#include <windows.h>
#endif

#include "Constants.h"
#include "core/chunk.h"
#include "core/voxel.h"
#include "generators/BiomeGenerator.h"
#include "generators/FeatureGenerator.h"
#include "generators/NoiseGenerator.h"

// Threading support
#include <atomic>
#include <condition_variable>
#include <deque>
#include <mutex>
#include <queue>
#include <shared_mutex>
#include <thread>
#include <unordered_map>
#include <vector>

#include <godot_cpp/classes/area3d.hpp>
#include <godot_cpp/classes/collision_shape3d.hpp>
#include <godot_cpp/classes/fast_noise_lite.hpp>
#include <godot_cpp/classes/immediate_mesh.hpp>
#include <godot_cpp/classes/material.hpp>
#include <godot_cpp/classes/mesh_instance3d.hpp>
#include <godot_cpp/classes/node3d.hpp>
#include <godot_cpp/classes/shader_material.hpp>
#include <godot_cpp/classes/static_body3d.hpp>
#include <godot_cpp/classes/worker_thread_pool.hpp>
#include <godot_cpp/core/class_db.hpp>
#include <godot_cpp/variant/color.hpp>
#include <godot_cpp/variant/packed_color_array.hpp>
#include <godot_cpp/variant/packed_string_array.hpp>
#include <godot_cpp/variant/packed_vector3_array.hpp>
#include <godot_cpp/variant/vector3.hpp>

using namespace godot;

namespace voxel_engine {

// Struct to hold mesh data generated by worker threads
struct ChunkMeshData {
	int chunk_index;
	Vector3i chunk_coord;
	PackedVector3Array vertices;
	PackedVector3Array normals;
	PackedColorArray colors;
	PackedColorArray custom0; // Custom per-vertex data (e.g., biome id)
};

// Generation mode enum - determines how terrain is generated
enum GenerationMode {
	VOXELS_FIRST = 0, // Full 3D density evaluation (current behavior)
	HEIGHTMAP_FIRST = 1 // 2D heightmap then surface band only (optimized)
};

/// @brief VoxelGenerator: Core terrain generation engine with async support and LOD.
///
/// This class manages voxel terrain generation, including:
/// - Procedural noise-based terrain with configurable amplitude and detail
/// - Async mesh generation via WorkerThreadPool for non-blocking performance
/// - Per-chunk Level-of-Detail (LOD) adjustment based on distance
/// - Terraforming (dig/build spheres) with terrain edit persistence
/// - Forcefield (world boundary walls) for containment
/// - Save/load map functionality with compression support
///
/// @note DEPRECATED: Direct instantiation is discouraged. Use VoxelEngine::create_generator()
/// instead to ensure proper lifecycle management and ownership. Direct VoxelGenerator
/// instantiation may lead to cleanup issues if not managed carefully.
///
/// Example (correct usage):
/// @code
/// var engine = VoxelEngine.new()
/// var generator = engine.create_generator()  # Owned by engine, auto-cleaned up
/// @endcode
///
/// Example (deprecated usage - may cause cleanup issues):
/// @code
/// var generator = VoxelGenerator.new()  # NOT RECOMMENDED - manually managed
/// @endcode
///
class VoxelGenerator : public Node3D {
	GDCLASS(VoxelGenerator, Node3D)

private:
	// Generation mode and LOD settings
	GenerationMode generation_mode = HEIGHTMAP_FIRST;
	float surface_band = 4.0f; // Vertical band around surface for heightmap mode
	int lod_level = 7; // Global LOD level (0 = highest detail, 7 = lowest)
	int heightmap_vertex_limit = voxel_engine::MAX_VERTICES_HEIGHTMAP; // Vertex limit for heightmap mode (8x standard)

	// Distance-based LOD settings (per-chunk LOD)
	bool enable_distance_lod = false; // Enable per-chunk LOD based on distance from reference
	Vector3 lod_reference_position = Vector3(0, 0, 0); // Position to measure distance from (camera/player)
	PackedFloat64Array lod_distances; // Distance thresholds for LOD levels 0-7 (8 values)
	bool lod_distances_custom = false; // True if user has set custom LOD distances
	float lod_distance_multiplier = 2.0f; // Multiplier for LOD distance formula (default 2.0 = double per LOD)
	bool show_lod_colors = false; // Visualize LOD levels with color-coded chunks
	bool use_textures = false; // Toggle textured shader vs vertex-color debug output
	Ref<Material> terrain_material; // Optional shared terrain material applied to all chunks

	// Heightmap cache for HEIGHTMAP_FIRST mode
	std::vector<float> heightmap_cache;
	int heightmap_size_x = 0;
	int heightmap_size_z = 0;

	// Terrain generation properties
	Ref<NoiseGenerator> terrain_noise; // 2D noise for base terrain height
	Ref<NoiseGenerator> detail_noise; // 3D noise for rocky detail
	Ref<BiomeGenerator> biome_generator; // Biome generation (sibling to feature_generator)
	Ref<FeatureGenerator> feature_generator; // Feature/decoration generation (sibling to biome_generator)
	float rock_influence = 0.3f; // Strength of rocky detail (0.0-1.0)
	float terrain_height = 4.0f; // Base terrain height in world units
	float terrain_amplitude = 8.0f; // Height variation range

	// Vertical placement offset: allows aligning voxel volume center to biome sample mid-height
	float world_vertical_center_offset = 0.0f;

	Vector3i world_size = Vector3i(1, 1, 1);
	Vector3i world_size_locked = Vector3i(1, 1, 1); // Locked size to prevent offset drift
	bool world_size_finalized = false; // True after first generation (prevents size changes)
	int resolution = 1;
	float cutoff = 0.0f;
	bool show_centers = false;
	bool show_voxel_grid = false;
	bool show_chunk_grid = false;
	bool randomizer = false;
	int seeder = 1240;
	bool auto_generate = false;
	bool vertex_limit = false; // Limit the number of vertices generated

	// Debug properties
	bool debug_mode = true;
	bool visualize_noise_values = false;
	int debug_verbosity = 1;

	// Add a container for chunks, e.g.:
	std::vector<Chunk *> chunks;
	int chunk_size = Constants::DEFAULT_CHUNK_SIZE; // Default value from voxel_constants.h

	// ==================== Threading & Density Cache ====================
	// Density cache for marching cubes optimization (stores corner densities)
	std::vector<float> density_cache;
	int cache_size_x = 0; // Number of corner points in X (total_voxels_x + 1)
	int cache_size_y = 0; // Number of corner points in Y (total_voxels_y + 1)
	int cache_size_z = 0; // Number of corner points in Z (total_voxels_z + 1)
	int cache_resolution = 1; // The effective resolution the cache was built with
	Vector3 cache_voxel_size = Vector3(1.0f, 1.0f, 1.0f); // Voxel size used when cache was built
	bool cache_is_valid = false; // True if density cache is current and can be reused

	// ==================== Terrain Edits Storage ====================
	// Maps voxel index (packed x,y,z) to density delta
	// Positive delta = more solid (build), Negative delta = less solid (dig)
	std::unordered_map<uint64_t, float> terrain_edits;
	mutable std::mutex terrain_edits_mutex; // Protects terrain_edits map

	// Procedural feature edits baked during generation (kept separate from runtime edits)
	std::unordered_map<uint64_t, float> feature_density_edits;
	mutable std::mutex feature_edits_mutex;

	// Helper to pack voxel coordinates into a single key
	inline uint64_t pack_edit_key(int x, int y, int z) const {
		// Pack 3 signed 20-bit values into 64 bits (supports ±524,287 range)
		uint64_t ux = static_cast<uint64_t>(x + 524288) & 0xFFFFF;
		uint64_t uy = static_cast<uint64_t>(y + 524288) & 0xFFFFF;
		uint64_t uz = static_cast<uint64_t>(z + 524288) & 0xFFFFF;
		return (ux << 40) | (uy << 20) | uz;
	}
	// =================================================================

	// Thread synchronization primitives
	mutable std::shared_mutex density_cache_mutex; // Read-write lock for density cache
	mutable std::mutex chunks_mutex; // Protects chunks vector modifications
	std::atomic<bool> generation_in_progress{ false }; // Prevents concurrent generate() calls

	// Chunk dirty flags for incremental updates (protected by chunks_mutex)
	std::vector<bool> chunk_dirty_flags;

	// ==================== Async Generation State ====================
	// Queue for mesh data ready to be applied on main thread
	std::queue<ChunkMeshData> pending_mesh_queue;
	mutable std::mutex mesh_queue_mutex; // Protects pending_mesh_queue

	// WorkerThreadPool task group for async generation
	WorkerThreadPool::GroupID async_task_group = 0;
	std::atomic<int> chunks_completed{ 0 };
	std::atomic<bool> cancel_requested{ false };
	int total_chunks = 0;

	// Configurable async generation properties
	int max_chunks_per_frame = 4; // Max chunks to apply mesh per frame (1-32)
	int signal_every_n_chunks = 8; // Emit progress signal every N chunks (1-64)
	int last_signal_count = 0; // Track last signal emission point
	// ==================================================================
	// ===================================================================

	const bool object_instance_binding_set_by_parent_constructor;
	bool has_object_instance_binding() const;

protected:
	static void _bind_methods();
	// This method is called to notify the object of various events.
	void _notification(int p_what);

public:
	VoxelGenerator();
	~VoxelGenerator();

	void set_world_size(const Vector3i &value);
	Vector3i get_world_size() const;

	// Terrain noise getters/setters
	void set_terrain_noise(const Ref<NoiseGenerator> &p_noise);
	Ref<NoiseGenerator> get_terrain_noise() const;

	void set_detail_noise(const Ref<NoiseGenerator> &p_noise);
	Ref<NoiseGenerator> get_detail_noise() const;

	void set_rock_influence(float value);
	float get_rock_influence() const;

	void set_terrain_height(float value);
	float get_terrain_height() const;

	void set_terrain_amplitude(float value);
	float get_terrain_amplitude() const;

	// Biome generator (sibling to feature generator)
	void set_biome_generator(const Ref<BiomeGenerator> &p_generator);
	Ref<BiomeGenerator> get_biome_generator() const;

	// Feature generator (sibling to biome generator)
	void set_feature_generator(const Ref<FeatureGenerator> &p_generator);
	Ref<FeatureGenerator> get_feature_generator() const;

	void set_resolution(int value);
	int get_resolution() const;

	void set_cutoff(float value);
	float get_cutoff() const;

	void set_randomizer(bool value);
	bool get_randomizer() const;

	void set_show_centers(bool value);
	bool get_show_centers() const;

	void set_show_voxel_grid(bool value);
	bool get_show_voxel_grid() const;

	void set_show_chunk_grid(bool value);
	bool get_show_chunk_grid() const;

	void set_seeder(int value);
	int get_seeder() const;

	void set_auto_generate(bool value);
	bool get_auto_generate() const;

	void set_vertex_limit(bool value);
	bool get_vertex_limit() const;

	void set_chunk_size(int value);
	int get_chunk_size() const;

	// Generation mode and LOD getters/setters
	void set_generation_mode(int value);
	int get_generation_mode() const;

	void set_surface_band(float value);
	float get_surface_band() const;

	void set_lod_level(int value);
	int get_lod_level() const;

	void set_heightmap_vertex_limit(int value);
	int get_heightmap_vertex_limit() const;

	// Distance-based LOD API
	void set_enable_distance_lod(bool value);
	bool get_enable_distance_lod() const;

	void set_lod_reference_position(const Vector3 &value);
	Vector3 get_lod_reference_position() const;

	void set_lod_distances(const PackedFloat64Array &value);
	PackedFloat64Array get_lod_distances() const;

	void reset_lod_distances_to_default();
	int calculate_chunk_lod(int chunk_index) const;
	Vector3 get_chunk_center_world_position(int chunk_index) const;
	int update_chunks_lod(); // Returns count of chunks that need regeneration

	void set_lod_distance_multiplier(float value);
	float get_lod_distance_multiplier() const;

	void set_show_lod_colors(bool value);
	bool get_show_lod_colors() const;

	void set_use_textures(bool value);
	bool get_use_textures() const;

	void set_terrain_material(const Ref<Material> &value);
	Ref<Material> get_terrain_material() const;

	// Get LOD color for visualization (green=LOD0 to red=LOD7)
	Color get_lod_color(int lod_level) const;

	void reset();

	void generate();
	void generate_async();
	void cancel_generation();
	bool is_generating() const;

	// Configurable async properties
	void set_max_chunks_per_frame(int value);
	int get_max_chunks_per_frame() const;

	void set_signal_every_n_chunks(int value);
	int get_signal_every_n_chunks() const;

	// Process callback for streaming mesh application
	void _process(double delta);

	// Debug methods
	void set_debug_mode(bool p_enabled);
	bool get_debug_mode() const;

	void set_visualize_noise_values(bool p_enabled);
	bool get_visualize_noise_values() const;

	void set_debug_verbosity(int p_level);
	int get_debug_verbosity() const;

	void debug_print_state();
	void debug_draw_noise_slice(float y_level);
	void log_message(const String &message, int verbosity_level = 1);

	bool is_object_binding_set_by_parent_constructor() const;

	// Sampling API exposed for external callers (e.g., VoxelEngine facade)
	// Returns the procedural+edited density at a world position (negative = solid).
	float sample_density_at(const Vector3 &world_pos) const;
	// Get voxel type at integer world voxel coordinates. Returns VoxelType (0 = AIR).
	int get_voxel_at(const Vector3i &voxel_pos) const;

	// ==================== Chunk Dirty Flag API ====================
	// Mark a specific chunk as needing regeneration
	void mark_chunk_dirty(const Vector3i &chunk_coord);
	// Mark all chunks as dirty
	void mark_all_chunks_dirty();
	// Check if a chunk is dirty
	bool is_chunk_dirty(const Vector3i &chunk_coord) const;
	// Regenerate only dirty chunks (incremental update)
	void regenerate_dirty_chunks();
	// Invalidate density cache for a region (call when terrain is edited)
	void invalidate_density_region(const Vector3i &min_voxel, const Vector3i &max_voxel);
	// ==============================================================

	// ==================== Terraforming API ====================
	// Modify terrain in a spherical region with smooth falloff
	// center: world position of edit center
	// radius: radius of effect in world units
	// delta: density change (negative = dig, positive = build)
	void modify_terrain(const Vector3 &center, float radius, float delta);

	// Convenience functions for digging (removes terrain)
	void dig_sphere(const Vector3 &center, float radius, float strength = 1.0f);

	// Convenience functions for building (adds terrain)
	void build_sphere(const Vector3 &center, float radius, float strength = 1.0f);

	// Clear all terrain edits (reset to original procedural terrain)
	void clear_terrain_edits();

	// Get number of stored terrain edits
	int get_terrain_edit_count() const;

	// Serialization for save/load
	PackedFloat32Array get_terrain_edits_data() const;
	void set_terrain_edits_data(const PackedFloat32Array &data);
	// ===========================================================

	// ==================== Forcefield (world boundary) ====================
	// Managed as scene children under this Node3D (main-thread only)
	bool forcefield_enabled = false;
	bool forcefield_collision_enabled = true;
	bool forcefield_detection_enabled = true;
	float forcefield_height = 300.0f;
	float forcefield_buffer = 0.5f; // inward buffer from exact world boundary

	Node3D *forcefield_root = nullptr; // container for wall nodes
	// Forcefield shader material (assignable in Inspector)
	Ref<ShaderMaterial> forcefield_shader_material;

	// Detection zone size expressed in voxels (controls detection area thickness)
	float forcefield_detection_voxels = 3.0f;
	// Extended to support 6 walls: north, south, east, west, top, bottom
	enum ForcefieldWall {
		FF_NORTH = 0,
		FF_SOUTH = 1,
		FF_EAST = 2,
		FF_WEST = 3,
		FF_TOP = 4,
		FF_BOTTOM = 5,
		FF_COUNT = 6
	};
	MeshInstance3D *forcefield_wall_meshes[FF_COUNT] = { nullptr, nullptr, nullptr, nullptr, nullptr, nullptr }; // 0=north,1=south,2=east,3=west,4=top,5=bottom
	StaticBody3D *forcefield_bodies[FF_COUNT] = { nullptr, nullptr, nullptr, nullptr, nullptr, nullptr };
	CollisionShape3D *forcefield_shapes[FF_COUNT] = { nullptr, nullptr, nullptr, nullptr, nullptr, nullptr };
	Area3D *forcefield_areas[FF_COUNT] = { nullptr, nullptr, nullptr, nullptr, nullptr, nullptr };

	// Keep track of how many bodies are inside each forcefield area so we
	// only hide the visual wall when the last body exits.
	int forcefield_body_counts[FF_COUNT] = { 0, 0, 0, 0, 0, 0 };

	// Per-wall enabled flags (Inspector-exposed wrappers will map to these)
	bool forcefield_wall_enabled[FF_COUNT] = { true, true, true, true, true, true };

	// Forcefield API
	void set_forcefield_enabled(bool enabled);
	bool get_forcefield_enabled() const;

	void set_forcefield_height(float h);
	float get_forcefield_height() const;

	void set_forcefield_collision_enabled(bool enabled);
	bool get_forcefield_collision_enabled() const;

	void set_forcefield_detection_enabled(bool enabled);
	bool get_forcefield_detection_enabled() const;

	void set_forcefield_buffer(float buf);
	float get_forcefield_buffer() const;

	// Forcefield shader material (assignable in Inspector)
	void set_forcefield_shader_material(const Ref<ShaderMaterial> &material);
	Ref<ShaderMaterial> get_forcefield_shader_material() const;

	// Indexed per-wall API (0..FF_COUNT-1). Validates index.
	void set_forcefield_wall_enabled(int wall_index, bool enabled);
	bool get_forcefield_wall_enabled(int wall_index) const;

	void set_forcefield_wall_collision_enabled(int wall_index, bool enabled);
	bool get_forcefield_wall_collision_enabled(int wall_index) const;

	void set_forcefield_wall_detection_enabled(int wall_index, bool enabled);
	bool get_forcefield_wall_detection_enabled(int wall_index) const;

	// Named convenience wrappers for Inspector exposure
	void set_forcefield_north_enabled(bool enabled);
	bool get_forcefield_north_enabled() const;
	void set_forcefield_south_enabled(bool enabled);
	bool get_forcefield_south_enabled() const;
	void set_forcefield_east_enabled(bool enabled);
	bool get_forcefield_east_enabled() const;
	void set_forcefield_west_enabled(bool enabled);
	bool get_forcefield_west_enabled() const;
	void set_forcefield_top_enabled(bool enabled);
	bool get_forcefield_top_enabled() const;
	void set_forcefield_bottom_enabled(bool enabled);
	bool get_forcefield_bottom_enabled() const;

	// Detection zone size (voxels)
	void set_forcefield_detection_voxels(float voxels);
	float get_forcefield_detection_voxels() const;

	// Debug helper: returns material info for the four forcefield walls
	PackedStringArray get_forcefield_material_info() const;

	// Set a parameter on the forcefield shader at runtime
	void set_forcefield_shader_param(const String &param, const Variant &value);

	// Create/destroy/update forcefield nodes (main thread)
	void create_forcefield_nodes();
	void update_forcefield_nodes();
	void remove_forcefield_nodes();

	// Detection callbacks invoked from Area signals (main thread)
	void on_forcefield_body_entered(Object *body, int wall_index);
	void on_forcefield_body_exited(Object *body, int wall_index);

	// Save / Load map API
	// dir: base directory (e.g. "user://saved_maps"), map_name: subfolder name
	void save_map(const String &dir, const String &map_name);
	void load_map(const String &dir, const String &map_name, bool strict_match = true);

	// Background writer control (internal)
	void start_background_writer();
	void stop_background_writer();

	// =====================================================================

private:
	// ---------------- Background writer / save queue ----------------
	struct MeshWriteJob {
		int chunk_index = -1;
		Vector3i chunk_coord = Vector3i(-1, -1, -1);
		String filename; // relative filename to write
		std::vector<float> vertices;
		std::vector<float> normals;
		std::vector<uint8_t> colors; // RGBA bytes
		std::vector<uint8_t> custom0; // custom per-vertex data (packed)
	};

	std::thread background_writer;
	std::deque<MeshWriteJob> writer_queue;
	std::mutex writer_mutex;
	std::condition_variable writer_cv;
	std::atomic<bool> writer_running{ false };
	String writer_out_dir;
	// -----------------------------------------------------------------
	void remove_children();
	void randomize_seed();
	Vector<Vector3> create_cube_vertices(const Vector3 &pos);
	void add_cubes_vertices(Ref<ImmediateMesh> mesh, const Vector<Vector3> &vertices);
	float get_terrain_density(const Vector3 &pos) const;
	std::vector<float> get_cube_values(const Vector<Vector3> &cube_vertices);
	int get_lookup_index(const std::vector<float> &cube_values, float cutoff);
	Vector3 interpolate(const Vector3 &vertex_1, float value_1, const Vector3 &vertex_2, float value_2);
	void add_cube_edges(Ref<ImmediateMesh> mesh, const std::vector<Vector3> &v);
	void calculate_world_size();

	// Debug helpers
	void create_debug_visualization();
	void visualize_noise_field();

	// Helper to rebuild debug visualizations after generation
	void rebuild_debug_visualizations();

	// Initialize default LOD distances based on chunk_size
	void initialize_default_lod_distances();

	// Get effective resolution for a specific LOD level
	int get_effective_resolution_for_lod(int lod) const;

	// Optionally, add helpers to manage chunks/voxels
	void create_chunks();
	void fill_chunk_with_voxels(Chunk *chunk);

	// Derived voxel scale (physical size per sample). For Option A: resolution = samples per voxel edge
	// base_voxel_size: computed from raw resolution setting (1.0 / resolution)
	// effective_voxel_size: computed from LOD-adjusted resolution (1.0 / get_effective_resolution())
	Vector3 base_voxel_size = Vector3(1, 1, 1);
	Vector3 effective_voxel_size = Vector3(1, 1, 1);

	// Recalculate both voxel sizes when world/chunk/resolution/LOD parameters change
	void recalculate_voxel_scale();

	bool is_instance_valid(Chunk *chunk) const;

	// Procedural biome/feature helpers
	void prepare_procedural_features();
	int generate_chunk_features(const Vector3i &chunk_coord);
	void bake_feature_descriptor(const Dictionary &feature);
	void apply_feature_density_sphere(const Vector3 &center, float radius, float delta);
	Vector3 get_chunk_world_origin(const Vector3i &chunk_coord) const;
	float sample_raw_base_height(float world_x, float world_z) const;
	float sample_base_height(float world_x, float world_z) const;
	Color get_biome_debug_color(int biome_index) const;
	void ensure_vertical_extent_for_biomes();

	// ==================== Density Cache Methods ====================
	// Build the density cache for all corner positions (call at start of generate())
	void build_density_cache();
	// Clear the density cache to free memory (call at end of generate() or on reset)
	void clear_density_cache();
	// Get cached density value (thread-safe read)
	float get_cached_density(int ix, int iy, int iz) const;
	// Convert 3D index to 1D cache index
	inline int density_cache_index(int ix, int iy, int iz) const {
		return ix + iy * cache_size_x + iz * cache_size_x * cache_size_y;
	}
	// Get cube corner values from cache (optimized version)
	std::vector<float> get_cube_values_cached(int ix, int iy, int iz) const;
	// Get density at world position using trilinear interpolation from cache
	float get_density_at_world_position(const Vector3 &world_pos) const;
	// Get cube corner values at world position (for LOD-independent sampling)
	std::vector<float> get_cube_values_at_world_position(const Vector3 &center, const Vector3 &half_size) const;
	// Convert chunk coordinate to linear index
	int chunk_coord_to_index(const Vector3i &chunk_coord) const;
	// Convert linear index to chunk coordinate
	Vector3i index_to_chunk_coord(int index) const;
	// ==============================================================

	// ==================== Async Generation ====================
	// Static callback for WorkerThreadPool
	static void _chunk_generation_task(void *userdata, uint32_t chunk_index);
	// Internal chunk mesh generation (called from worker thread)
	void generate_chunk_mesh_internal(int chunk_index);
	// Synchronous per-chunk mesh generation (called from main thread)
	// override_lod: -1 = use distance-based or global LOD, 0-7 = force specific LOD
	void generate_chunk_mesh_sync(int chunk_index, int override_lod = -1);
	// Queue mesh data for main thread application
	void queue_mesh_data(const ChunkMeshData &mesh_data);
	// Apply pending mesh data from queue (called from _process on main thread)
	void apply_pending_meshes();
	// Clear pending mesh queue (called on cancel)
	void clear_pending_meshes();
	// ===========================================================

	// ==================== Generation Mode Methods ====================
	// Generate terrain using full 3D voxel evaluation (original method)
	void generate_voxels_first(Ref<ImmediateMesh> mesh_centers, Ref<ImmediateMesh> mesh_cubes,
			Ref<ImmediateMesh> mesh_triangles, int &centers_vertex_count, int &cubes_vertex_count, int &vertex_count);
	// Generate terrain using 2D heightmap then surface band optimization
	void generate_heightmap_first(Ref<ImmediateMesh> mesh_centers, Ref<ImmediateMesh> mesh_cubes,
			Ref<ImmediateMesh> mesh_triangles, int &centers_vertex_count, int &cubes_vertex_count, int &vertex_count);
	// Get effective resolution considering LOD level
	int get_effective_resolution() const;
	// Get effective surface band considering LOD level
	float get_effective_surface_band() const;

	// Get cached height value at grid position
	float get_height_at(float fx, float fz) const;
	// =================================================================

	// ==================== Heightmap Cache Methods ====================
	// Build the 2D heightmap cache (call at start of heightmap-first generation)
	void build_heightmap_cache();
	// Clear the heightmap cache
	void clear_heightmap_cache();
	// Convert 2D index to 1D cache index
	inline int heightmap_cache_index(int ix, int iz) const {
		return ix + iz * heightmap_size_x;
	}
	// Check if terrain noise has changed (requires heightmap rebuild)
	bool heightmap_needs_rebuild() const;
	// ==================================================================

	// ==================== Feature Application Methods ====================
	// Apply features to generated terrain (returns number of placements baked)
	int apply_features_to_chunk(Chunk *chunk);
	// Get surface heights for a chunk region (for feature placement)
	TypedArray<int> get_chunk_surface_heights(const Vector3i &chunk_coord) const;
	// Get biome indices for a chunk region (for feature placement)
	TypedArray<int> get_chunk_biome_indices(const Vector3i &chunk_coord) const;
	// =====================================================================
};
} // namespace voxel_engine

#endif // VOXEL_GENERATOR_H